# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"8\n\x0cLoginRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x15\n\ruser_password\x18\x02 \x01(\t\"P\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x14\n\x0c\x65rror_detail\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"4\n\x10Login_vkResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"A\n\x0f\x63\x61llbackRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\"=\n\x10\x63\x61llbackResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"6\n\x13RegistrationRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"A\n\x14RegistrationResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t2\xf2\x01\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12/\n\x08Login_vk\x12\x0b.auth.Empty\x1a\x16.auth.Login_vkResponse\x12\x39\n\x08\x63\x61llback\x12\x15.auth.callbackRequest\x1a\x16.auth.callbackResponse\x12\x45\n\x0cRegistration\x12\x19.auth.RegistrationRequest\x1a\x1a.auth.RegistrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=76
  _globals['_LOGINRESPONSE']._serialized_start=78
  _globals['_LOGINRESPONSE']._serialized_end=158
  _globals['_EMPTY']._serialized_start=160
  _globals['_EMPTY']._serialized_end=167
  _globals['_LOGIN_VKRESPONSE']._serialized_start=169
  _globals['_LOGIN_VKRESPONSE']._serialized_end=221
  _globals['_CALLBACKREQUEST']._serialized_start=223
  _globals['_CALLBACKREQUEST']._serialized_end=288
  _globals['_CALLBACKRESPONSE']._serialized_start=290
  _globals['_CALLBACKRESPONSE']._serialized_end=351
  _globals['_REGISTRATIONREQUEST']._serialized_start=353
  _globals['_REGISTRATIONREQUEST']._serialized_end=407
  _globals['_REGISTRATIONRESPONSE']._serialized_start=409
  _globals['_REGISTRATIONRESPONSE']._serialized_end=474
  _globals['_AUTHSERVICE']._serialized_start=477
  _globals['_AUTHSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
