# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"P\n\nGetRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x18\n\x10selected_columns\x18\x02 \x01(\t\x12\x19\n\x11rule_of_selection\x18\x03 \x01(\t\"5\n\x0bGetResponse\x12\x11\n\tdata_json\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"?\n\x0bPostRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12!\n\x19inserted_columns_and_data\x18\x02 \x01(\t\"#\n\x0cPostResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"k\n\rUpdateRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12!\n\x19inserted_columns_and_data\x18\x02 \x01(\t\x12\x17\n\x0fname_of_item_id\x18\x03 \x01(\t\x12\x0f\n\x07item_id\x18\x04 \x01(\t\"%\n\x0eUpdateResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"H\n\rDeleteRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x17\n\x0fname_of_item_id\x18\x02 \x01(\t\x12\x0f\n\x07item_id\x18\x03 \x01(\t\"%\n\x0e\x44\x65leteResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32\xf6\x01\n\x0f\x44\x61tabaseService\x12\x32\n\x03Get\x12\x14.database.GetRequest\x1a\x15.database.GetResponse\x12\x35\n\x04Post\x12\x15.database.PostRequest\x1a\x16.database.PostResponse\x12;\n\x06Update\x12\x17.database.UpdateRequest\x1a\x18.database.UpdateResponse\x12;\n\x06\x44\x65lete\x12\x17.database.DeleteRequest\x1a\x18.database.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=28
  _globals['_GETREQUEST']._serialized_end=108
  _globals['_GETRESPONSE']._serialized_start=110
  _globals['_GETRESPONSE']._serialized_end=163
  _globals['_POSTREQUEST']._serialized_start=165
  _globals['_POSTREQUEST']._serialized_end=228
  _globals['_POSTRESPONSE']._serialized_start=230
  _globals['_POSTRESPONSE']._serialized_end=265
  _globals['_UPDATEREQUEST']._serialized_start=267
  _globals['_UPDATEREQUEST']._serialized_end=374
  _globals['_UPDATERESPONSE']._serialized_start=376
  _globals['_UPDATERESPONSE']._serialized_end=413
  _globals['_DELETEREQUEST']._serialized_start=415
  _globals['_DELETEREQUEST']._serialized_end=487
  _globals['_DELETERESPONSE']._serialized_start=489
  _globals['_DELETERESPONSE']._serialized_end=526
  _globals['_DATABASESERVICE']._serialized_start=529
  _globals['_DATABASESERVICE']._serialized_end=775
# @@protoc_insertion_point(module_scope)
